//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.02 at 01:47:00 AM IST 
//


package org.hl7.elm.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The ToString operator converts the value of its argument to a String value. The operator uses the following string representations for each type:
 * 
 * Boolean true|false
 * Integer (-)?#0
 * Decimal (-)?#0.0#
 * Quantity (-)?#0.0# '<unit>'
 * DateTime YYYY-MM-DDThh:mm:ss.fff(+|-)hh:mm
 * Time	Thh:mm:ss.fff(+|-)hh:mm
 * 
 * If the argument is null, the result is null.
 * 
 * <p>Java class for ToString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToString">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:elm:r1}UnaryExpression">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToString")
public class ToString
    extends UnaryExpression
{


}
